Reception/Web/Areas/Admin/Controllers/FaqsController.cs
using System;
using System.Threading.Tasks;
using DataAccess.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Model.Entities;

namespace Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admins,SuperAdmin")]
    [Area("Admin")]
    public class FaqsController : Controller
    {
        private IFaq _faq;

        public FaqsController(IFaq faq)
        {
            _faq = faq;
        }


        // GET: Admin/Faqs
        public async Task<IActionResult> Index()
        {
            return View(_faq.GetAll());
        }

        // GET: Admin/Faqs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faq = _faq.GetById(id.Value);
            if (faq == null)
            {
                return NotFound();
            }

            return View(faq);
        }

        // GET: Admin/Faqs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Faqs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FaqId,FaqTitle,FaqAnswer,DateCreate,UserName")] Faq faq)
        {
            if (ModelState.IsValid)
            {
                faq.InsertDate = DateTime.Now;
                faq.UpDateTime=DateTime.Now;
                _faq.Add(faq);
                _faq.Save();
                return RedirectToAction(nameof(Index), "Faqs",new {area="Admin"});
            }
            return View(faq);
        }

        // GET: Admin/Faqs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faq = _faq.GetById(id.Value);
            if (faq == null)
            {
                return NotFound();
            }
            return View(faq);
        }

        // POST: Admin/Faqs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FaqId,FaqTitle,FaqAnswer,DateCreate,UserName")] Faq faq)
        {
            if (id != faq.FaqId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    faq.UpDateTime=DateTime.Now;
                    _faq.Update(faq);
                    _faq.Save();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FaqExists(faq.FaqId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "Faqs", new { area = "Admin" });

            }
            return View(faq);
        }

        // GET: Admin/Faqs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faq = _faq.GetById(id.Value);
            if (faq == null)
            {
                return NotFound();
            }

            return View(faq);
        }

        // POST: Admin/Faqs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var faq = _faq.GetById(id);
           _faq.Delete(faq);
           return RedirectToAction(nameof(Index), "Faqs", new { area = "Admin" });

        }

        private bool FaqExists(int id)
        {
            return _faq.Exist(id);
        }
    }
}

Reception/Web/Areas/Admin/Controllers/VideoController.cs
using System;
using System.Threading.Tasks;
using DataAccess.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Model.Entities;

namespace Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admins,SuperAdmin")]
    [Area("Admin")]
    public class VideoController : Controller
    {
        private IVideo _video;

        public VideoController(IVideo video)
        {
            _video = video;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _video.GetAll());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _video.GetById(id.Value);
            if (video == null)
            {
                return NotFound();
            }

            return View(video);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VideoId,Title,Link,Description,InsertDate,IsDelete,UpDateTime")] Video video)
        {
            if (ModelState.IsValid)
            {
                video.InsertDate = DateTime.Now;
                video.UpDateTime=DateTime.Now;
                _video.Add(video);

                return RedirectToAction(nameof(Index), "Video");
            }
            return View(video);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _video.GetById(id.Value);
            if (video == null)
            {
                return NotFound();
            }
            return View(video);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VideoId,Title,Link,Description,InsertDate,IsDelete,UpDateTime")] Video video)
        {
            if (id != video.VideoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    video.UpDateTime = DateTime.Now;
                    _video.Update(video);

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VideoExists(video.VideoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "Video");
            }
            return View(video);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var video = await _video.GetById(id.Value);

            if (video == null)
            {
                return NotFound();
            }

            return View(video);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var video = await _video.GetById(id);
            _video.Delete(video);

            return RedirectToAction(nameof(Index), "Video");
        }

        private bool VideoExists(int id)
        {
            return _video.Exist(id);
        }
    }
}

Reception/Web/Controllers/LearnController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataAccess.Interfaces;

namespace Web.Controllers
{
    public class LearnController : Controller
    {
        private IFaq _faq;

        public LearnController(IFaq faq)
        {
            _faq = faq;
        }
        public IActionResult Articles()
        {

            return View();
        }
        public IActionResult Videos()
        {
            return View();
        }
        public IActionResult Faqs(string search,int take , int pageId=1)
        {
            
            var model = _faq.GetAll(25,pageId);
            return View(model);
        }
    }
}

Reception/Web/Views/Learn/Articles.cshtml
@{
    ViewData["Title"] = "Articles";
}

<h1>Articles</h1>

Reception/Web/Views/Learn/Faqs.cshtml
@model Tuple<List<Model.Entities.Faq>,int>
@{
    ViewData["Title"] = "Faqs";
}

<div class="content   flex-column-fluid" id="kt_content">
    <!--begin::زیر هدر-->
    <div class="subheader py-3 py-lg-2  subheader-transparent " id="kt_subheader" kt-hidden-height="90" style="">
        <div class=" container  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
            <!--begin::اطلاعات-->
            <div class="d-flex align-items-center flex-wrap mr-1">

                <!--begin::Page Heading-->
                <div class="d-flex align-items-baseline flex-wrap mr-5">
                    <!--begin::Page Title-->
                    <h2 class="subheader-title text-dark font-weight-bold my-1 mr-3">
                        فروشگاه بیت
                    </h2>
                    <!--end::Page Title-->
                    <!--begin::Breadcrumb-->
                    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold my-2 p-0">
                        <li class="breadcrumb-item">
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="text-muted">
                                خانه
                            </a>
                        </li>
                        <li class="breadcrumb-item">
                            <a asp-area="" asp-controller="Learn" asp-action="Faqs" class="text-muted">
                                سوالات متداول
                            </a>
                        </li>
                    </ul>
                    <!--end::Breadcrumb-->
                </div>
                <!--end::Page Heading-->
            </div>
            <!--end::اطلاعات-->

        </div>
    </div>
    <!--end::زیر هدر-->
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class=" container ">

            @foreach (var item in Model.Item1)
            {
                <!--begin::کارت-->
                <div class="card card-custom card-stretch example example-compact" id="kt_page_stretched_card">
                    <div class="card-header ribbon ribbon-clip ribbon-left">
                        <div class="ribbon-target" style="top: 12px;">
                            <span class="ribbon-inner bg-success"></span>@item.FaqTitle
                        </div>
                        <div class="card-title">
                            <h3 class="card-label">
                            </h3>
                        </div>

                    </div>
                    <div class="card-body">
                        @*<div class="card-scroll" >*@
                            <!--begin::کد example-->
                            <p>
                                @Html.Raw(item.FaqAnswer)
                            </p>
                            <!--end::کد example-->

                        @*</div>*@
                    </div>
                </div>
                <!--end::کارت-->
            }

        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
</div>

Reception/Web/Views/Learn/Videos.cshtml
@{
    ViewData["Title"] = "Videos";
}

<h1>Videos</h1>